#!/usr/bin/env sh
sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

yabai -m config layout bsp
yabai -m config window_placement first_child
yabai -m config window_topmost on
yabai -m config mouse_modifier fn

yabai -m config window_shadow float
yabai -m config window_opacity on
yabai -m config active_window_opacity 0.9
yabai -m config normal_window_opacity 0.8
yabai -m config menubar_opacity 0.5


yabai -m config rule "app='System Settings' manage=off"

echo "profile: A♥a"                                                                                       
